services:
  server:
    image: docker.io/filebrowser/filebrowser:v2.45.2@sha256:bb8a99a9151ea6ca840520b80307d938145bebd102e799435062fec460752163
    volumes:
      - type: bind
        source: /
        target: /root
        bind:
          create_host_path: false
      - type: bind
        source: /
        target: /srv # this prevents filebrowser from making an unnamed volume
        bind:
          create_host_path: false
      - server-data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/root
    user: root
networks:
  default:
    name: none
    external: true
volumes:
  server-data: {}
