services:
  server:
    image: docker.io/filebrowser/filebrowser:v2.45.3@sha256:0f178042e05263265078ab788aed69b0f0ae64d7de3efc3ebff177774e29a13d
    volumes:
      - type: bind
        source: /
        target: /root
        bind:
          create_host_path: false
      - type: bind
        source: /
        target: /srv # this prevents filebrowser from making an unnamed volume
        bind:
          create_host_path: false
      - server-data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/root
    user: root
networks:
  default:
    name: none
    external: true
volumes:
  server-data: {}
